name: Build Desktop App

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build macOS
        run: pyinstaller "Kobo Highlights Exporter.spec"

      - name: Debug dist contents
        run: ls -R dist

      - name: Package macOS
        run: |
          cp README.md dist/
          cd dist
          zip -r KoboHighlightsExporter-${{ github.event.release.tag_name }}-macOS.zip .

      - name: Upload macOS asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/KoboHighlightsExporter-${{ github.event.release.tag_name }}-macOS.zip


  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Linux
        run: pyinstaller "Kobo Highlights Exporter.spec"

      - name: Debug dist contents
        run: ls -R dist

      - name: Package Linux
        run: |
          cp README.md dist/
          cd dist
          tar czf KoboHighlightsExporter-${{ github.event.release.tag_name }}-Linux.tar.gz .

      - name: Upload Linux asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/KoboHighlightsExporter-${{ github.event.release.tag_name }}-Linux.tar.gz
